# Generated by Django 5.2.8 on 2025-11-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionemocional',
            old_name='emocion_detectada',
            new_name='emocion',
        ),
        migrations.RenameField(
            model_name='evaluacionemocional',
            old_name='texto_analizado',
            new_name='recomendacion',
        ),
        migrations.AddField(
            model_name='evaluacionemocional',
            name='texto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacionemocional',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='api.usuario'),
        ),
    ]
